repository:
  name: test
  description: ''
  homepage: ''
  private: false
  has_issues: false
  has_wiki: false
  has_downloads: false
  default_branch: develop
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true

labels:
  - name: bug
    color: CC0000
  - name: feature
    color: 336699

collaborators:
  - username: timlangley
    permission: push

  - username: dblencowe
    permission: admin